name: release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip"
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - run: python -m pip install -r _patch/requirements.txt
      - run: python _patch/build.py
        shell: bash

      - uses: softprops/action-gh-release@v2
        with:
          files: "dist/*"
